words["verbs"] = {
    "type": "verbit",
    "words" : [
        {"fi":"heittää", "en":"to throw", "ru":"бросать", "img": "img/heittää.png"},
        {"fi":"pelata", "en":"to play", "ru":"играть", "img": "img/pelata.png"},
        {"fi":"syöttää", "en":"to feed", "ru":"кормить", "img": "img/syöttää.png"},
        {"fi":"syöttää", "en":"to pass", "ru":"делать пас", "img": "img/pass.jpg"},
        {"fi":"luistella", "en":"to skate", "ru":"кататься"},
        {"fi":"päästää", "en":"to release", "ru":"освобождать", "img" : "img/päästää.png"},
        {"fi":"estää", "en":"to prevent, to stop", "ru":"останавливать, запрещать", "img": "img/estää.png"},
        {"fi":"hypätä", "en":"to jump", "ru":"прыгать", "img": "img/hypätä.png"},
        {"fi":"potkaista", "en":"to kick", "ru":"пинать", "img": "img/potkaista.png"},
        {"fi":"uida", "en":"to swim", "ru":"плавать", "img":"img/uida.png"},
        {"fi":"kertoa", "en":"to tell", "ru":"рассказывать"},
        {"fi":"lähteä", "en":"to leave", "ru":"уходить"},
        {"fi":"mennä", "en":"to go", "ru":"идти", "img":"img/mennä.png"},
        {"fi":"löytää", "en":"to find", "ru":"найти", "img":"img/löytää.png"},
        {"fi":"etsiä", "en":"to search", "ru":"искать"},
        {"fi":"ottaa", "en":"to take", "ru":"брать", "img":"img/ottaa.jpg", "snd":"sounds/ottaa.mp3"},
        {"fi":"saapua", "en":"to arrive", "ru":"прибывать"},
        {"fi":"yöpyä", "en":"to sleep", "ru":"спать"},
        {"fi":"nähdä", "en": "to see", "ru":"видеть"},
        {"fi":"juosta", "en":"to run", "ru":"бежать"},
        {"fi":"juoda", "en":"to drink", "ru":"пить"},
        {"fi":"saada", "en":"to receive", "ru":"получать"},
        {"fi":"saada", "en":"to have permission (may)", "ru":"иметь право"},
        {"fi":"voida", "en":"to be able to", "ru":"мочь, быть, иметь"},
        {"fi":"antaa", "en":"to give", "ru":"давать"},
        {"fi":"juhlia", "en":"to celebrate", "ru":"праздновать"},
        {"fi":"avata", "en":"to open", "ru":"открывать"},
        {"fi":"valita", "en":"to choose", "ru":"выбирать"},
        {"fi":"nousta", "en":"to rise, to get up", "ru":"вставать, подниматься"},
        {"fi":"soida", "en":"to play sound", "ru":"звучать"},
        {"fi":"herätä", "en":"to wake up", "ru":"просыпаться"},
        {"fi":"opiskella", "en":"to study", "ru":"учиться"},
        {"fi":"hymyillä", "en":"to smile", "ru":"улыбаться"},
        {"fi":"tulla", "en":"to come, to become", "ru":"приходить, становиться"},
        {"fi":"korjata", "en":"to fix", "ru":"чинить"},
        {"fi":"siivota", "en":"to clean up", "ru":"прибирать"},
        {"fi":"häiritä", "en":"to disturb", "ru":"мешать кому-то"},
        {"fi":"myydä", "en":"to sell", "ru":"продавать"},
        {"fi":"imuroida", "en":"to vacuum", "ru":"пылесосить"},
        {"fi":"asua", "en":"to live", "ru":"жить"},
        {"fi":"pestä", "en":"to wash", "ru":"мыть, стирать"}
    ]
};