words["kappale2_1"] = {
    "type": "Kappale 2-1",
    "words" : [
        {"fi":"jäädä", "en":"to stay", "ru": "оставаться"},
        {"fi":"myöhästyä", "en":"to be late" },
        {"fi":"ehtiä", "en":"to reach" },
        {"fi":"hajota", "en":"to break down" },
        {"fi":"yrittää", "en":"to try" },
        {"fi":"järjestää", "en":"to arrange, to organize" },
        {"fi":"pelätä", "en":"to be afraid" },
        {"fi":"päästä", "en":"to arrive at"},
        {"fi":"aloittaa", "en":"to begin, to start"},
        {"fi":"laahustaa", "en":"to slouch, walk sickly", "ru": "сутулиться"},
        {"fi":"kokeilla", "en":"to sample, to try out", "ru": "пробовать"},
        {"fi":"keittää", "en":"to boil", "ru": "кипятить"},
        {"fi":"kurkistaa", "en":"to peek", "ru": "выглядывать"},

        {"fi":"kuuluisa", "en":"famous", "ru": "стройный"},
        {"fi":"vesiputous", "en":"waterfall", "ru": "водопад"},
        {"fi":"retki", "en":"trip", "ru": "путешествие"},
        {"fi":"jäljellä", "en":"left (adj)", "ru": "осталось"},
        {"fi":"vasta", "en":"only", "ru": "только"},
        {"fi":"kuljetus", "en":"transport" },
        {"fi":"varmaan", "en":"surely, undoubtedly" },
        {"fi":"inhottava", "en":"disgusting, nasty" },
        {"fi":"joten", "en":"so"},
        {"fi":"turha", "en":"useless"},
        {"fi":"enää", "en":"anymore"},
        {"fi":"itse asiassa", "en":"actually, in fact"},
        {"fi":"ylimääräinen", "en":"excessive, additional"},
        {"fi":"tuliainen", "en":"souvenir"},
        {"fi":"ajatus", "en":"thought, idea"},
        {"fi":"mielelläni", "en":"with pleasure"},
        {"fi":"reissu", "en":"journey"},
        {"fi":"paluu", "en":"return, comeback"},
        {"fi":"meno", "en":"going, course"},
        {"fi":"majoitus", "en":"accommodation, shelter"},
        {"fi":"nähtävyys", "en":"sight, attraction"},
        {"fi":"kiertoajelu", "en":"sightseeing tour"},
        {"fi":"kamala", "en":"horrible"},
        {"fi":"paha", "en":"evil, bad"},
        {"fi":"puhdas", "en":"tidy, pure"},
        {"fi":"rentouttava", "en":"relaxing"},
        {"fi":"sateinen", "en":"rainy"},
        {"fi":"siisti", "en":"tidy, neat"},
        {"fi":"tärkeä", "en":"important, major"},
        {"fi":"terveellinen", "en":"healthy"},
        {"fi":"tylsä", "en":"boring, dull"},
        
        {"fi":"sairas", "en":"sick", "ru": "больной"},
        {"fi":"olo", "en":"feeling", "ru": "чувство"},
        {"fi":"Minulla on huono olo", "en":"I feel bad, sick", "ru": "Я себя плохо чувствую", "img":"img/huono_olo.jpg"},
        {"fi":"nuha", "en":"running nose", "ru": "течет нос"},
        {"fi":"särkeä", "en":"ache", "ru": "боль"},
        {"fi":"lopulta", "en":"eventually", "ru": "в конце концов"},
        {"fi":"ainoa", "en":"only, lone", "ru": "только, одинокий"},
        {"fi":"ahdas", "en":"cramped, tight", "ru": "ограниченный"},
        {"fi":"taitaa", "en":"may", "ru": "может"},
        {"fi":"oire", "en":"symptom", "ru": "симптом"},
        {"fi":"vilustunut", "en":"Having cold", "ru": "простужен"},
        {"fi":"tulehdus", "en":"inflammation", "ru": "воспаление"},
        {"fi":"yskä", "en":"cough", "ru": "кашель"},
        {"fi":"vatsatauti", "en":"stomach flu", "ru": "кишечный грипп"},
        {"fi":"haava", "en":"wound", "ru": "рана"},
        {"fi":"kätilö", "en":"midwife", "ru": "акушерка"},
        {"fi":"päivystys", "en":"service, duty", "ru": "сервис"},
        {"fi":"tauti", "en":"disease", "ru": "болезнь"},
        {"fi":"huuli", "en":"lip", "ru": "губа"},
        {"fi":"vatsa", "en":"belly", "ru": "живот"},
        {"fi":"maha", "en":"stomach", "ru": "желудок"}
       
    ]
};
