words["kappale4"] = {
    "type": "Kappale 4-7",
    "words" : [
        {"fi":"hoikka", "en":"slim", "ru": "стройный"},
        {"fi":"söpö", "en":"cute", "ru": "милый"},
        {"fi":"ujo", "en":"shy", "ru": "застенчивый"},
        {"fi":"suloinen", "en":"sweet", "ru": "сладенький"},
        {"fi":"bussikuski", "en":"bus driver", "ru": "водитель автобуса"},
        {"fi":"tukka", "en":"hair", "ru": "волосы"},
        {"fi":"suora", "en":"straight", "ru": "прямые"},
        {"fi":"kihara", "en":"curly", "ru": "кудрявый"},
        {"fi":"puhelias", "en":"talkative", "ru": "разговорчивый"},
        {"fi":"hiljainen", "en":"quiet", "ru": "тихий"},
        {"fi":"vihainen", "en":"evil", "ru": "злой"},
        {"fi":"kohtelias", "en":"polite", "ru": "вежливый"},
        {"fi":"epäkohtelias", "en":"impolite", "ru": "невежливый"},
        {"fi":"parta", "en":"beard", "ru": "борода"},
        {"fi":"viikset", "en":"mustache", "ru": "усы"},
        {"fi":"komea", "en":"handsome", "ru": "красивый"},
        {"fi":"tukeva", "en":"sturdy", "ru": "плотный"},
        {"fi":"kihloissa", "en":"engaged", "ru": "обручен"},
        {"fi":"eronnut", "en":"divorced", "ru": "разведен"},
        {"fi":"avoliitossa", "en":"cohabiting", "ru": "сожительствовать"},
        {"fi":"avoliitto", "en":"cohabitation", "ru": "сожительствование"},
        {"fi":"parempi", "en":"better", "ru": "лучше"},
        {"fi":"lomake", "en":"form (to fill)", "ru": "форма (для заполнения)"},
        {"fi":"haluta", "en":"to want", "ru": "хотеть"},
        {"fi":"ilmoittautua", "en":"to register", "ru": "зарегистрироваться"},
        {"fi":"tarkistaa", "en":"to check", "ru": "проверить"},
        {"fi":"tarvita", "en":"need", "ru": "нуждаться"},
        {"fi":"siviilisääty", "en":"martial status", "ru": "семейное положение"},
        {"fi":"henkilötiedot", "en":"personal details", "ru": "персональные данные"},
        {"fi":"nälkä", "en":"hunger", "ru": "голод"},
        {"fi":"jano", "en":"thirst", "ru": "жажда"},
        {"fi":"kiire", "en":"hurry", "ru": "спешка"},
        {"fi":"Minulla on nälkä", "en":"I'm hungry", "ru": "Я голодный", "snd":"sounds/nälkä.mp3", "img":"img/nälkä.jpg"},
        {"fi":"Minulla on jano", "en":"I'm thursty", "ru": "У меня жажда", "snd":"sounds/jano.mp3", "img":"img/jano.jpg"},
        {"fi":"Minulla on kiire", "en":"I'm in a hurry", "ru": "Я спешу", "snd":"sounds/kiire.mp3", "img":"img/kiire.jpg"},
        {"fi":"tavallisesti", "en":"usually", "ru": "обычно"},
        {"fi":"heti", "en":"right now", "ru": "немедленно"},
        {"fi":"vielä", "en":"yet, still, more", "ru": "еще"},
        {"fi":"lattia", "en":"floor", "ru": "пол (в комнате)"},
        {"fi":"pehmeä", "en":"soft", "ru": "мягкий"},
        {"fi":"kova", "en":"hard", "ru": "жесткий"},
        {"fi":"leveä", "en":"wide", "ru": "широкий"},
        {"fi":"kapea", "en":"narrow", "ru": "узкий"},
        {"fi":"sänky", "en":"bed", "ru": "кровать"},
        {"fi":"matala", "en":"low", "ru": "низкий"},
        {"fi":"seinä", "en":"wall", "ru": "стена"},
        {"fi":"viihtyisä", "en":"homey, comfortable", "ru": "удобный"},
        {"fi":"sotkuinen", "en":"messy", "ru": "беспорядочный"},
        {"fi":"tässä", "en":"here", "ru": "тут", "img":"img/tässä.png"},
        {"fi":"tuo", "en":"that", "ru": "этот"},
        {"fi":"usein", "en":"often", "ru": "часто"},
        {"fi":"jo", "en":"already", "ru": "уже"},
        {"fi":"aika", "en":"quite (small)", "ru": "довольно (маленький)", "img":"img/quite_small.jpg"},
        {"fi":"aika", "en":"time", "ru": "время"},
        {"fi":"ongelma", "en":"problem", "ru": "проблема"},
        {"fi":"vika", "en":"fault", "ru": "отказ"},
        {"fi":"kunnolla", "en":"properly", "ru": "правильно"},
        {"fi":"kiinni", "en":"closed", "ru": "закрыто"},
        {"fi":"koko ajan", "en":"all the time", "ru": "все время", "img":"img/koko_ajan.jpg"},
        {"fi":"selvä juttu", "en":"all clear", "ru": "все понятно", "img":"img/all_clear.png"},
        {"fi":"hieno", "en":"great!", "ru": "отлично"},
        {"fi":"rappu", "en":"stair", "ru": "подъезд"},
        {"fi":"nostaa", "en":"to lift", "ru": "поднимать"},
        {"fi":"kantaa", "en":"to carry", "ru": "нести"},
        {"fi":"tapahtua", "en":"to happen", "ru": "случаться"},
        {"fi":"viedä", "en":"to carry out", "ru": "относить"},
        {"fi":"tuoda", "en":"to carry in", "ru": "приносить"},
        {"fi":"käydä", "en":"to visit", "ru": "посещать"},
        {"fi":"vuotaa", "en":"to leak", "ru": "протекать"},
        {"fi":"sopia", "en":"to fit", "ru": "подходить"},
        {"fi":"katsella", "en":"to watch", "ru": "смотреть"},
        {"fi":"palata", "en":"to return", "ru": "вернуться"},
        {"fi":"viipyä", "en":"to be late", "ru": "задерживаться"},
        {"fi":"tarkistaa", "en":"to check", "ru": "проверять"},
        {"fi":"luovuttaa", "en":"to hand over", "ru": "отдавать"},
        {"fi":"lossi", "en":"ferry", "ru": "паром"},
        {"fi":"teltta", "en":"tent", "ru": "палатка"},
        {"fi":"mennään", "en":"lets go", "ru": "пойдем"},
        {"fi":"varmasti", "en":"certainly", "ru": "конечно"},
        {"fi":"mukava", "en":"comfortable", "ru": "удобный"},
        {"fi":"noin", "en":"about, around", "ru": "примерно"},
        {"fi":"...-kin", "en":"...-also", "ru": "...-тоже, также", "img":"img/kin.jpg"},
        {"fi":"henki", "en":"spirit", "ru": "дух"},
        {"fi":"täytyä", "en":"have to", "ru": "должен"},
        {"fi":"lause", "en":"sentence", "ru": "предложение (текст)"},
        {"fi":"tuore", "en":"fresh", "ru": "свежий"},
        {"fi":"ihminen", "en":"human", "ru": "человек"},
        {"fi":"yhdistää", "en":"to connect", "ru": "соединять"},
        {"fi":"panna", "en":"to put", "ru": "ставить"},
        {"fi":"toimisto", "en":"office", "ru": "офис"},
        {"fi":"sairaala", "en":"hospital", "ru": "больница"},
        {"fi":"ainakin", "en":"at least", "ru": "как минимум"},
        {"fi":"aina", "en":"always", "ru": "всегда"},
        {"fi":"taas", "en":"again", "ru": "опять"}        
    ]
};
