words["kappale2_1"] = {
    "type": "Kappale 2-1",
    "words" : [
        {"fi":"jäädä", "en":"to stay", "ru": "оставаться"},
        {"fi":"myöhästyä", "en":"to be late" },
        {"fi":"ehtiä", "en":"to reach" },
        {"fi":"hajota", "en":"to break down" },
        {"fi":"yrittää", "en":"to try" },
        {"fi":"järjestää", "en":"to arrange, to organize" },
        {"fi":"pelätä", "en":"to be afraid" },
        {"fi":"päästä", "en":"to arrive at"},
        {"fi":"aloittaa", "en":"to begin, to start"},

        {"fi":"kuuluisa", "en":"famous", "ru": "стройный"},
        {"fi":"vesiputous", "en":"waterfall", "ru": "водопад"},
        {"fi":"retki", "en":"trip", "ru": "путешествие"},
        {"fi":"jäljellä ", "en":"left (adj)", "ru": "осталось"},
        {"fi":"vasta", "en":"only", "ru": "только"},
        {"fi":"kuljetus", "en":"transport" },
        {"fi":"varmaan", "en":"surely, undoubtedly" },
        {"fi":"inhottava", "en":"disgusting, nasty" },
        {"fi":"joten", "en":"so"},
        {"fi":"turha", "en":"useless"},
        {"fi":"enää", "en":"anymore"},
        {"fi":"itse asiassa", "en":"actually, in fact"},
        {"fi":"ylimääräinen", "en":"excessive, additional"},
        {"fi":"tuliainen", "en":"souvenir"},
        {"fi":"ajatus", "en":"thought, idea"},
        {"fi":"mielelläni", "en":"with pleasure"},
        {"fi":"reissu", "en":"journey"},
        {"fi":"paluu", "en":"return, comeback"},
        {"fi":"meno", "en":"going, course"},
        {"fi":"majoitus", "en":"accommodation, shelter"},
        {"fi":"nähtävyys", "en":"sight, attraction"},
        {"fi":"kiertoajelu", "en":"sightseeing tour"},
        {"fi":"kamala", "en":"horrible"},
        {"fi":"paha", "en":"evil, bad"},
        {"fi":"puhdas", "en":"tidy, pure"},
        {"fi":"rentouttava", "en":"relaxing"},
        {"fi":"sateinen", "en":"rainy"},
        {"fi":"siisti", "en":"tidy, neat"},
        {"fi":"tärkeä", "en":"important, major"},
        {"fi":"terveellinen", "en":"healthy"},
        {"fi":"tylsä", "en":"boring, dull"}        
    ]
};
