words["kappale10"] = {
    "type": "Kappale 10+",
    "words" : [
        {"fi":"jaksaa", "en":"to keep doing", "ru": "продолжать делать"},
        {"fi":"luulla", "en":"to guess, to suppose", "ru": "предполагать"},
        {"fi":"tutkia", "en":"to examine, to explore", "ru": "изучать, исследовать"},
        {"fi":"esitellä", "en":"to demonstrate", "ru": "демонстрировать"},
        {"fi":"neuvotella", "en":"to negotiate", "ru": "договариваться"},
        {"fi":"tuntea", "en":"to know someone, to feel", "ru": "знать кого-то"},
        {"fi":"pyytää", "en":"to request, to ask", "ru": "спрашивать"},
        {"fi":"petata", "en":"to make a bed", "ru": "заправлять кровать"},
        {"fi":"jakaa", "en":"to distribute", "ru": "раздавать"},
        {"fi":"näkyä", "en":"to be visible", "ru": "быть видимым"},
        {"fi":"pukeutua", "en":"to dress", "ru": "одеваться"},
        {"fi":"kutsua", "en":"to call", "ru": "вызывать"},
        {"fi":"vaikuttaa", "en":"to influence", "ru": "влиять"},
        {"fi":"sattua", "en":"to occur, to happen", "ru": "случаться"},
        {"fi":"kestää", "en":"to last, to endure", "ru": "выдерживать"},
        {"fi":"sai", "en":"received", "ru": "получил"},
        {"fi":"toi", "en":"brought", "ru": "принёс"},

        {"fi":"rakentaa", "en":"to build", "ru": "строить"},
        {"fi":"harjoitella", "en":"to practice", "ru": "практиковаться"},
        {"fi":"suunnitella", "en":"to design, to plan", "ru": "планировать"},
        {"fi":"kadota", "en":"to disappear", "ru": "исчезать"},
        {"fi":"maata", "en":"to lie down", "ru": "лежать"},
        {"fi":"levätä", "en":"to rest", "ru": "отдыхать"},
        {"fi":"suudella", "en":"to kiss", "ru": "целовать"},
        {"fi":"kammata", "en":"to comb", "ru": "расчёсываться"},

        {"fi":"joukko", "en":"set", "ru": "множество"},
        {"fi":"tyhjä", "en":"empty", "ru": "пустой"},
        {"fi":"likainen", "en":"dirty", "ru": "грязный"},
        {"fi":"enää", "en":"anymore", "ru": "больше..."},
        {"fi":"kevyt", "en":"light", "ru": "легкий"},
        {"fi":"ehkä", "en":"perhaps", "ru": "возможно"},
        {"fi":"patsas", "en":"statue", "ru": "статуя"},
        {"fi":"pensas", "en":"bush", "ru": "куст"},
        {"fi":"kiva", "en":"nice", "ru": "хороший"},
        {"fi":"mieli", "en":"mind", "ru": "разум"},
        {"fi":"mielipide", "en":"opinion", "ru": "мнение"},
        {"fi":"raskas", "en":"heavy", "ru": "трудный"},

        {"fi":"haku", "en":"search", "ru": "поиск"},
        {"fi":"käynnissä", "en":"in progress", "ru": "в прогрессе"},
        {"fi":"käynti", "en":"a visit", "ru": "посещение"},
        {"fi":"lempi", "en":"favorite", "ru": "любимая..."},
        {"fi":"äärimmäinen", "en":"extremelly", "ru": "очень, экстремально"},
        {"fi":"yhteinen", "en":"common", "ru": "общий"},
        {"fi":"vahinko", "en":"damage, injury", "ru": "вред, травма"},

        {"fi":"vakava", "en":"serious", "ru": "серьёзный"},
        {"fi":"ihan totta", "en":"Really!", "ru": "Точно!"},
        {"fi":"isku", "en":"impact, blow", "ru": "столкновение, удар"},
        {"fi":"hyökkäys", "en":"attack, assault", "ru": "атака, нападение"},
        {"fi":"pako", "en":"getaway, escape", "ru": "бегство"},
        {"fi":"pakolainen", "en":"refugee", "ru": "беженец"}
    ]
};
