words["verbs"] = {
    "type": "Verbs",
    "words" : [
        {"fi":"heittää", "en":"to throw", "ru":"бросать", "img": "img/heittää.png"},
        {"fi":"pelata", "en":"to play", "ru":"играть", "img": "img/pelata.png"},
        {"fi":"syöttää", "en":"to feed", "ru":"кормить", "img": "img/syöttää.png"},
        {"fi":"syöttää", "en":"to pass", "ru":"делать пас", "img": "img/pass.jpg"},
        {"fi":"luistella", "en":"to skate", "ru":"кататься"},
        {"fi":"päästää", "en":"to release", "ru":"освобождать", "img" : "img/päästää.png"},
        {"fi":"estää", "en":"to prevent, to stop", "ru":"останавливать, запрещать", "img": "img/estää.png"},
        {"fi":"hypätä", "en":"to jump", "ru":"прыгать", "img": "img/hypätä.png"},
        {"fi":"potkaista", "en":"to kick", "ru":"пинать", "img": "img/potkaista.png"},
        {"fi":"uida", "en":"to swim", "ru":"плавать", "img":"img/uida.png"},
        {"fi":"kertoa", "en":"to tell", "ru":"рассказывать"},
        {"fi":"lähteä", "en":"to leave", "ru":"уходить"},
        {"fi":"mennä", "en":"to go", "ru":"идти", "img":"img/mennä.png"},
        {"fi":"löytää", "en":"to find", "ru":"найти", "img":"img/löytää.png"},
        {"fi":"etsiä", "en":"to search", "ru":"искать"},
        {"fi":"ottaa", "en":"to take", "ru":"брать", "img":"img/ottaa.jpg", "snd":"sounds/ottaa.mp3"},
        {"fi":"saapua", "en":"to arrive", "ru":"прибывать"},
        {"fi":"yöpyä", "en":"to sleep", "ru":"спать"},
        {"fi":"nähdä", "en": "to see", "ru":"видеть"},
        {"fi":"juosta", "en":"to run", "ru":"бежать"},
        {"fi":"juoda", "en":"to drink", "ru":"пить"},
        {"fi":"saada", "en":"to receive", "ru":"получать"},
        {"fi":"saada", "en":"to have permission (may)", "ru":"иметь право"},
        {"fi":"voida", "en":"to be able to", "ru":"мочь, быть, иметь"},
        {"fi":"antaa", "en":"to give", "ru":"давать"},
        {"fi":"juhlia", "en":"to celebrate", "ru":"праздновать"},
        {"fi":"avata", "en":"to open", "ru":"открывать"},
        {"fi":"valita", "en":"to choose", "ru":"выбирать"},
        {"fi":"nousta", "en":"to rise, to get up", "ru":"вставать, подниматься"},
        {"fi":"soida", "en":"to play sound", "ru":"звучать"},
        {"fi":"herätä", "en":"to wake up", "ru":"просыпаться"},
        {"fi":"opiskella", "en":"to study", "ru":"учиться"},
        {"fi":"hymyillä", "en":"to smile", "ru":"улыбаться"},
        {"fi":"tulla", "en":"to come, to become", "ru":"приходить, становиться"},
        {"fi":"korjata", "en":"to fix", "ru":"чинить"},
        {"fi":"siivota", "en":"to clean up", "ru":"прибирать"},
        {"fi":"häiritä", "en":"to disturb", "ru":"мешать кому-то"},
        {"fi":"myydä", "en":"to sell", "ru":"продавать"},
        {"fi":"imuroida", "en":"to vacuum", "ru":"пылесосить"},
        {"fi":"asua", "en":"to live", "ru":"жить"},
        {"fi":"pestä", "en":"to wash", "ru":"мыть, стирать"},
        {"fi":"seisoa", "en":"to stand", "ru":"стоять"},
        {"fi":"sovittaa", "en":"to match, to fit", "ru":"мерять, подходить"},
        {"fi":"nostaa", "en":"to lift", "ru": "поднимать"},
        {"fi":"kantaa", "en":"to carry", "ru": "нести"},
        {"fi":"tapahtua", "en":"to happen", "ru": "случаться"},
        {"fi":"viedä", "en":"to carry out", "ru": "относить"},
        {"fi":"tuoda", "en":"to carry in", "ru": "приносить"},
        {"fi":"käydä", "en":"to visit", "ru": "посещать"},
        {"fi":"vuotaa", "en":"to leak", "ru": "протекать"},
        {"fi":"sopia", "en":"to fit", "ru": "подходить"},
        {"fi":"katsella", "en":"to watch", "ru": "смотреть"},
        {"fi":"palata", "en":"to return", "ru": "вернуться"},
        {"fi":"viipyä", "en":"to linger", "ru": "задерживаться"},
        {"fi":"tarkistaa", "en":"to check", "ru": "проверять"},
        {"fi":"luovuttaa", "en":"to hand over", "ru": "отдавать"},
        {"fi":"yhdistää", "en":"to connect", "ru": "соединять"},
        {"fi":"panna", "en":"to put", "ru": "ставить"},

        {"fi":"jaksaa", "en":"to keep doing", "ru": "продолжать делать"},
        {"fi":"luulla", "en":"to guess, to suppose", "ru": "предполагать"},
        {"fi":"tutkia", "en":"to examine, to explore", "ru": "изучать, исследовать"},
        {"fi":"esitellä", "en":"to demonstrate", "ru": "демонстрировать"},
        {"fi":"neuvotella", "en":"to negotiate", "ru": "договариваться"},
        {"fi":"tuntea", "en":"to know someone, to feel", "ru": "знать кого-то"},
        {"fi":"pyytää", "en":"to request, to ask", "ru": "спрашивать"},
        {"fi":"petata", "en":"to make a bed", "ru": "заправлять кровать"},

        {"fi":"jäädä", "en":"to stay", "ru": "оставаться"},
        {"fi":"myöhästyä", "en":"to be late", "ru": "опаздывать" },
        {"fi":"ehtiä", "en":"to reach", "ru": "достигать" },
        {"fi":"hajota", "en":"to break down", "ru": "ломаться" },
        {"fi":"yrittää", "en":"to try", "ru": "пробовать" },
        {"fi":"järjestää", "en":"to arrange, to organize", "ru": "организовывать" },
        {"fi":"pelätä", "en":"to be afraid", "ru": "бояться" },
        {"fi":"päästä", "en":"to arrive at", "ru": "прибывать"},
        {"fi":"aloittaa", "en":"to begin, to start", "ru": "начитать"}
        {"fi":"rakentaa", "en":"to build", "ru": "строить"},
        {"fi":"harjoitella", "en":"to practice", "ru": "практиковаться"},
        {"fi":"suunnitella", "en":"to design, to plan", "ru": "планировать"},
        {"fi":"kadota", "en":"to disappear", "ru": "исчезать"},
        {"fi":"maata", "en":"to lie down", "ru": "лежать"},
        {"fi":"levätä", "en":"to rest", "ru": "отдыхать"},
        {"fi":"suudella", "en":"to kiss", "ru": "целовать"},
        {"fi":"kammata", "en":"to comb", "ru": "расчёсываться"},

        {"fi":"laahustaa", "en":"to slouch, walk sickly", "ru": "сутулиться"},
        {"fi":"kokeilla", "en":"to sample, to try out", "ru": "пробовать"},
        {"fi":"keittää", "en":"to boil", "ru": "кипятить"},
        {"fi":"kurkistaa", "en":"to peek", "ru": "выглядывать"},
        {"fi":"jakaa", "en":"to distribute", "ru": "раздавать"},
        {"fi":"laskea", "en":"to decrease", "ru": "уменьшаться"},
        {"fi":"johtaa", "en":"to lead", "ru": "возглавлять"},
        {"fi":"suojata", "en":"to protect", "ru": "защищать"},
        {"fi":"näkyä", "en":"to be visible", "ru": "быть видимым"},
        {"fi":"kutsua", "en":"to call", "ru": "вызывать"},
        {"fi":"vaikuttaa", "en":"to influence", "ru": "влиять"},
        {"fi":"sattua", "en":"to occur, to happen", "ru": "случаться"},
        {"fi":"kestää", "en":"to last, to endure", "ru": "выдерживать"},
        {"fi":"sai", "en":"received", "ru": "получил"},
        {"fi":"toi", "en":"brought", "ru": "принёс"},

        {"fi":"huomata", "en":"to notice, to note", "ru": "замечать"},
        {"fi":"toimittaa", "en":"to deliver", "ru": "доставлять"},
        {"fi":"suositella", "en":"to recommend", "ru": "рекоммендовать"},
        {"fi":"möllöttää", "en":"to gape", "ru": "прозебать"},
        {"fi":"taipua", "en":"to bend, to yield", "ru": "гнуть, сдаваться"},
        {"fi":"huolehtia", "en":"to worry", "ru": "волноваться"},
        {"fi":"havaita", "en":"to detect", "ru": "обнаруживать"},
        {"fi":"vaatia", "en":"to demand", "ru": "требовать"},
        {"fi":"lastata", "en":"to load", "ru": "загружать"},
        {"fi":"purkaa", "en":"to unload, to diffuse", "ru": "выгружать"},
        {"fi":"liittää", "en":"to attach", "ru": "присоединять"},
        {"fi":"paljastaa", "en":"to reveal, to disclose", "ru": "выявлять, раскрывать"}
    ]
};